apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: world
  name: world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: world
    spec:
      containers:
      - name: world
        image: tum/world:latest
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: world
  name: world
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080    
  selector:
    app: world
